version: "3.0"
services:
  core_api:
    build: .
    image: core:core
    environment:
      - FLASK_APP=application.py
      - APP_SETTINGS=config.TestingConfig
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_BACKEND_URL=redis://redis/0
    volumes:
      - .:/src
    ports:
      - "8080:8080"
    command: uwsgi --http :8080 --module application:application --enable-threads
  redis:
    image: redis:5.0.7-alpine
    expose:
      - 6379
  celery_worker:
    image: core:core
    command: celery worker -A app.celery --loglevel=INFO
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_BACKEND_URL=redis://redis/0
    volumes:
      - .:/src
    depends_on:
      - redis
      - core_api
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888
    depends_on:
      - redis
      - celery_worker
